### ISSUE TITLE
Publish newest version as NPM module with perfect-scrollbar as peer dependency

### ISSUE THREAD

**Issue by mischkl** [itsdrewmiller/angular-perfect-scrollbar#95] opened 2018-02-08 13:26 UTC
It would be great if this could be updated to the newest version of perfect-scrollbar, and perhaps have it as a peer dependency.

**Comment by isherwood** [comment] 2018-02-08 13:28
This directive currently uses Perfect Scrollbar version 1.3.0, which is current. I agree that adding a peer dependency would be a good idea. Maybe someone will find time to make a pull request.

**Comment by mischkl** [comment] 2018-02-08 14:28
Hmm I suppose I was somewhat confused, I installed via NPM and received a package called "angular-perfect-scrollbar" with version 0.0.5 and a dependency on perfect-scrollbar v0.6.16.

I suppose a better title for this issue would be "Publish as NPM module".

**Comment by isherwood** [comment] 2018-02-08 14:36
Duplicate of #91 (the only other open issue :) ).

**Comment by isherwood** [comment] 2018-02-08 14:37
Closing as recognized. Please feel free to create a PR with the peer dependency change.

**Comment by mischkl** [comment] 2018-02-08 14:38
Aha right! PR submitted.

**Closed by isherwood** 2018-02-08 14:37 UTC
